### ISSUE TITLE
Hard deadline for CA7

### ISSUE THREAD

**Issue by mairtonbjr** [hshokrig/EP3260-MLoNs-2020#18]
Dear All,

In case you would like to update/finish your CA7, please do so until this Sunday, June 14. On Monday, June 14, we will assign the peer-review of the previous CAs.

Best Regards,
Mairton

**Comment by kvist3n** [comment]
Will there be a deadline for submitting peer reviews? I will be unavailable for 4 weeks.

**Comment by hshokrig** [comment]
Yes. it the end of next week. Please ask your teammates to cover for you.
